version: 2
jobs:
  build:
    docker:
      - image: seesharprun/dotnet-and-azure-cli:1.1.0
    working_directory: ~/source/
    steps:
      - checkout
      - run:
          name: Test Azure CLI
          command: az -v
      - run:
          name: Test DotNet CLI
          command: dotnet --version
      - run:
          working_directory: ~/source/
          name: Build Project
          command: dotnet build
      - run:
          working_directory: ~/source/
          name: Publish Project
          command: dotnet publish --configuration Release
      - store_artifacts:
          path: ~/source/CoreSolution.FunctionProject/bin/Release/netstandard2.0